### ISSUE TITLE
Song list shows for 1 frame

### ISSUE THREAD

**Issue by Khosumi** [halsafar/BeatSaberSongBrowser#165] opened 2021-08-15 03:37 UTC
Default song browser works fine, modded breaks as the video shows.
Restarting the game doesn't fix it, reinstalling the mod doesn't either. 

https://www.youtube.com/watch?v=AB67fvJohJo

**Comment by SmokyJoe88** [comment] 2021-08-18 00:01
same issue here.

**Comment by halsafar** [comment] 2021-08-31 22:36
This is a duplicate of #166, closing in favor of the discussion there.  Thanks for the report.

**Closed by halsafar** 2021-08-31 22:36 UTC
