### ISSUE TITLE
Delete Song Button does not fully remove song

### ISSUE THREAD

**Issue by zabes** [halsafar/BeatSaberSongBrowser#145] opened 2021-03-14 04:36 UTC
When Deleting a song it will delete it from in-game ui but does not actually remove it from the custom levels directory so when the song list is updated again, the deleted entry reappears. Seen with Steam version

**Comment by halsafar** [comment] 2021-03-28 16:39
SongBrowser actually uses SongCore to initiate the delete. This seems to be working fine for me using the latest SongCore.  SongCore's delete functionality is unchanged for the past >1yr.

I've tried reproducing this by deleting songs in Custom Levels category and All Songs category.  Does that match your steps?  Any extra details will help.

Is there potentially a file permission issue?

**Comment by Xandaros** [comment] 2021-03-29 21:37
I actually can't delete maps at all. It's like the button doesn't do anything.
That said, I have only tried this from within a playlists. I'll try from All Songs when I get the chance.

**Comment by Xandaros** [comment] 2021-03-30 13:50
Indeed, this only happens when I'm looking at a playlist, not when looking at all songs.

Does SongBrowser even touch the delete button at all or is that entirely SongCore?

**Comment by halsafar** [comment] 2021-04-04 00:25
Confirmed.  Just released 6.1.6 and did not address.  This will be addressed in the next release.

**Comment by halsafar** [comment] 2021-05-22 18:51
Will update here when the next release goes out, we can verify the fix and close this.

**Comment by halsafar** [comment] 2021-07-20 16:47
This was out with the last release.

**Closed** 2021-07-20 16:47 UTC
Labels: bug
