### ISSUE TITLE
I can't click the mod

### ISSUE THREAD

**Issue by sannier3** [halsafar/BeatSaberSongBrowser#169] opened 2021-09-03 14:26 UTC
I am giving away my current mods but I cannot click on the filters or anything else in the song browser without Beat Saber crashing
It works and displays but it does not work when clicked
[Link of the Zip for my Beat Saber mods](https://jbsan.fr/autre/beat_saber_mods/beat_saber_mods_1.17_JBSAN_V3.zip)

**Comment by sannier3** [comment] 2021-09-03 14:50
Ok, I'll add more precision. The button for random maps does not work and gives a black screen. If the filter is random and you click on it, the game also crashes

**Comment by halsafar** [comment] 2021-09-06 17:38
Confirmed, and the fix just got pushed.  I will do a release later today.  

This is also a duplicate of #171, so I'll close this when the release goes out.

**Comment by halsafar** [comment] 2021-09-06 17:43
Give this release a try:
https://github.com/halsafar/BeatSaberSongBrowser/releases/tag/6.3.1

**Closed** 2021-09-10 02:14 UTC
