### ISSUE TITLE
Playlist sorting breaks OST Vol 1 and 2

### ISSUE THREAD

**Issue by williums** [halsafar/BeatSaberSongBrowser#44] opened 2019-03-21 02:07 UTC
I went out of my way to try breaking this one, but I managed to replicate it consistently.

1. Select a playlist 
2. With the songs still sorted by playlist, click on OST Vol 1 or 2
3. Enter a song and return to the menu
4. The other OST volume continues to show the filtered custom songs, even after deselecting the playlist view. Extras and DLC content tabs appear to be unaffected.

**Comment by WesVleuten** [comment] 2019-03-23 20:13
Confirmed. We'll look into a fix

**Comment by halsafar** [comment] 2019-03-25 05:08
Fixed in 3.0.2.  Want to confirm?

**Comment by halsafar** [comment] 2019-03-27 04:52
Going to close as fixed.  This seems to be working well since 3.0.2.

**Closed** 2019-03-27 04:52 UTC
Labels: bug
