### ISSUE TITLE
Can't access Solo or Party mode after installing SongBrowser

### ISSUE THREAD

**Issue by amasuke55** [halsafar/BeatSaberSongBrowser#61] opened 2019-04-27 00:35 UTC
I can not click the Solo or Party buttons in the main menu after I install the SongBrowser plugin.
Campaign button works though.

**Comment by halsafar** [comment] 2019-05-08 18:21
Is this still happening in version 3.0.6 (latest)?

Can you run the game with `--verbose` and post a copy of the log.

**Comment by halsafar** [comment] 2019-06-13 15:38
No info.  Cannot reproduce.  We have progressed a few versions of Beat Saber and SongBrowser since this was reported.  Closing this.  Re-Open if more info is provided.

**Closed by halsafar** 2019-06-13 15:38 UTC
Labels: question
