### ISSUE TITLE
Can't select different song modes

### ISSUE THREAD

**Issue by FirEmerald** [halsafar/BeatSaberSongBrowser#98] opened 2019-12-16 03:32 UTC
With the mod installed, the song mode buttons (standard, one hand, no arrows, 360, 90) don't work. Affects the current version for 1.6.0

**Comment by halsafar** [comment] 2019-12-16 22:35
I am having trouble reproducing this one.  Is it possible for you to provide the path?  
I've tried this:
-  `Solo Mode` -> `Playlist` -> `360mode` -> Select song -> Change mode.
- `Solo Mode` -> OST/Custom Level -> Find a song with modes -> Change modes

If you can get the log there might be an exception you can provide which would help narrow down the cause.

**Comment by FirEmerald** [comment] 2019-12-16 22:46
I'll get on it later and edit this comment with the results, but for now I can confirm the bug was consistent and reproducible on my end.

**Comment by halsafar** [comment] 2019-12-17 01:43
For sure.  It is likely some interaction with a particular song or song+mode combo.

**Comment by halsafar** [comment] 2019-12-17 04:07
I managed to reproduce it!

**Comment by halsafar** [comment] 2019-12-17 04:15
Fixed.  Should have a release out in the next day.

**Comment by halsafar** [comment] 2019-12-17 23:56
6.0.1 Released with the fix.  Enjoy!

**Closed by halsafar** 2019-12-17 23:56 UTC
Labels: bug
