### ISSUE TITLE
Sort by PP is strange

### ISSUE THREAD

**Issue by Mattsassin** [halsafar/BeatSaberSongBrowser#21] opened 2018-10-31 16:37 UTC
When sorting by PP a bunch of songs show up that;
1. Share the same name as a ranked song
2. Show as a '?' as PP value when they are actually ranked
3. Aren't even ranked at all, nor share the same name, but display with a PP value

My song folders are all versioned, so I don't see why it would be working incorrectly. This may be the same bug I experienced with a previous version.

**Comment by halsafar** [comment] 2018-11-02 03:51
Definitely a bug there.  It is falling back to using song name sometimes or failing to use the song key.  I will address this next release.  I've got a few songs I can reproduce it with.

**Comment by halsafar** [comment] 2018-11-04 21:54
This should be fixed in 2.3.3.

Let me know.  I found a bunch of songs displaying incorrect information or missing information and they now display properly in 2.3.3.

**Comment by halsafar** [comment] 2018-11-09 00:54
I've confirmed a few hundred songs now.  I switched over to using the data I am scraping from scoresaber.  It parses easier, faster.  I also removed falling back to name matching.  Everything seems to be working as of 2.3.3.

**Closed by halsafar** 2018-11-09 00:54 UTC
