### ISSUE TITLE
Favorites and Sorting issues

### ISSUE THREAD

**Issue by Xplox55** [halsafar/BeatSaberSongBrowser#62] opened 2019-04-27 20:51 UTC
Hello,

Issue had started with favorites not being saved. Reinstalled mods, clean installed game, still the same issue. I would add a song as a favorite > favorite would be written to the .json in the playlists folder > In game still listed and showed 0 favorites.
It has now come to the point that any sorting (or I just didn't notice before) does not work. Below are the messages from --verbose regarding the SongBrowser.

Same issue occurs trying 3.0.5 and 3.0.4. Any ideas?

[INFO @ 15:44:21 | _] [SongBrowser @ 15:44 - Info] Determining song download time and determining mappings took 23ms
[INFO @ 15:44:21 | _] [SongBrowser @ 15:44 - Info] Updating songs infos took 31ms
[INFO @ 15:44:21 | _] [SongBrowser @ 15:44] SongBrowser UI crashed trying to update the internal song lists: -System.InvalidOperationException-Sequence contains no matching element
[INFO @ 15:44:21 | _]   at System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x00011] in <1b13ba6391c74847bbc3eddc86df7eee>:0
[INFO @ 15:44:21 | _]   at SongBrowser.UI.SongBrowserUI.GetLevelPackByPackId (System.String levelPackId) [0x00024] in <ac5e0b6aa24c4002af4ec9111ccb3efa>:0
[INFO @ 15:44:21 | _]   at SongBrowser.UI.SongBrowserUI.UpdateLevelPackSelection () [0x000fe] in <ac5e0b6aa24c4002af4ec9111ccb3efa>:0
[INFO @ 15:44:21 | _]   at SongBrowser.UI.SongBrowserUI.UpdateLevelDataModel () [0x00056] in <ac5e0b6aa24c4002af4ec9111ccb3efa>:0
[INFO @ 15:44:21 | _] [SongBrowser @ 15:44 - Info] Refreshing the song list view.
[INFO @ 15:44:21 | _] [BeatSaverDownloader | LOG] Selected pack: Custom Maps
[CRITICAL @ 15:44:21 | UnityEngine] NullReferenceException: Object reference not set to an instance of an object
[CRITICAL @ 15:44:21 | UnityEngine] CustomUI.Utilities.ReflectionUtil.GetPrivateField[T] (System.Object obj, System.String fieldName) (at <96cc36f4057440e49c8c3bc00a41dffb>:0)
[CRITICAL @ 15:44:21 | UnityEngine] BeatSaverDownloader.UI.SongListTweaks+<SelectLastPackAndSong>d__40.MoveNext () (at <63c8152f948244ea95448606b7d330cd>:0)
[CRITICAL @ 15:44:21 | UnityEngine] UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <1e56ad9145b44dbfa81599f39af43dd3>:0)
[INFO @ 15:44:23 | _] [SongBrowser @ 15:44 - Info] Refreshing the song list view.
[INFO @ 15:44:24 | _] [SongBrowser @ 15:44 - Info] Refreshing the song list view.

**Comment by Xplox55** [comment] 2019-05-10 14:40
I see there is a new version - I'll give 3.0.6 a try today and see if there's any difference!

**Comment by Xplox55** [comment] 2019-05-10 17:10
Same problem and error messages with 3.0.6 :/ I'm going to put in a new SSD in my system, install Beat Saber clean there and see if I get any different results.

**Comment by halsafar** [comment] 2019-05-19 18:39
Can just attach your `SongBrowserFavorites.json` file?   If you do not want to share it publicly then ping me on discord.  There is a good chance a few songs in the file are causing some exception and partially breaking functionality.

**Comment by Xplox55** [comment] 2019-05-21 08:56
Sent the .json in Discord.

**Comment by halsafar** [comment] 2019-05-29 02:40
I added a fix in 4.0.0+ that might address your issue.  I tested your favorites file and a few others.

**Comment by Xplox55** [comment] 2019-05-30 23:15
With version 4.1.0 installed, I can now successfully sort the favorites list.
The issue with some songs not showing up is still present, as well as the playlist not updating live when I add/remove songs from favorites. If I quit/reload the game, the favorites are then updated, but only with songs with a key of "key": "17520-19058". Keys that look like "key": "C7E33D948E63D57012B777F216E1551B∎Black lotus ∎Wa.∎Aithke∎200∎" still do not show up in the favorites list.
Thank you for the progress!

**Comment by halsafar** [comment] 2019-05-30 23:27
Glad we are making some progress. 

The info you just provided is very useful. I think I know where the problem is. I will update this when I have a fix. 

Thanks again!

**Comment by jb2kewl** [comment] 2019-06-07 20:12
Hello Halsafar.. I am having the same issue.. I also noticed that some song names have a single quote in them, which might be causing some issues as well.. I have attached my favorites file, so you can test out your fix, don't judge me!


[favoriteSongs - Copy.txt](https://github.com/halsafar/BeatSaberSongBrowser/files/3267431/favoriteSongs.-.Copy.txt)

**Comment by halsafar** [comment] 2019-06-09 02:40
That file is from Downloader.  SongBrowser uses `Playlists/SongBrowserFavorites.json`

**Comment by halsafar** [comment] 2019-06-09 02:50
I've discovered a bug however.  Might be related.

It seems if any song in your favorites list is not available for lookup on BeatSaver then all songs after it will not show up as a favorite.

**Comment by Xplox55** [comment] 2019-06-14 10:59
One thing I noticed while waiting for the 1.1.0 update - I had updated my game and installed other mods. While playing, my favorites playlist was displayed properly, and all of the songs were on there. So that's while not using the BSSongBrowser. Just wanted to add that the playlist displayed normally without the mod. Thanks!
Also thanks for getting V1.1.0 compatible out, going to be trying it out now!

**Comment by halsafar** [comment] 2019-06-14 21:54
Yah I haven't released anything yet.

**Comment by halsafar** [comment] 2019-06-15 07:05
5.0.0 is out.

**Comment by trinode** [comment] 2019-06-23 02:42
I'm having issues with favorites not loading with 5.0

Using just beatsaber downloader the format of the playlist is:
```
    {
      "newKey": "",
      "key": "1234",
      "songName": "Song Name ",
      "hash": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      "levelId": "custom_level_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    },

```

whereas when using SongBrowser the format is:

```
    {
      "key": "",
      "songName": "Song Name",
      "hash": "custom_level_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    }
```

So when you load the game after saving favorites, the list is empty but says "3 songs, 0 downloaded" for example.

Happy to test changes if required.

**Comment by halsafar** [comment] 2019-06-23 17:47
Confirmed.  There is actually two bugs here.  Fixed them both in the devel branch.  Will come with the next release.

Both fixes will automagically apply next time you add/remove a favorite using SongBrowser.  Then restart the game.

1. Writing levelId to hash field. Fixed by splitting out the hash.
2. Old favorites missing a hash only have a key, hit beatsaver to find the hash and update.

**Comment by Xplox55** [comment] 2019-06-24 02:06
Testing 5.0 I've lost a little bit of functionality. There are no longer any favorites in my favorites list, similar to the post above mine show 22 songs, 0 downloaded. Additionally, other filters are no longer working properly, in a way. (Plays, PP, etc.) As seen in the two screenshots, this song is always my top for plays - many failed attempts :) Title is now different post 5.0 update. Not sure if this means anything but I hope it helps, and I look forward to trying out the new fix release once it's out!
Pre 5.0.0 :
![image](https://user-images.githubusercontent.com/43867141/59986042-7e030300-95fa-11e9-85cf-343224d0b012.png)

Post 5.0.0 :
![image](https://user-images.githubusercontent.com/43867141/59986089-bb679080-95fa-11e9-913f-eaa041e3884e.png)

**Comment by halsafar** [comment] 2019-06-25 03:29
5.2.0 should hopefully address this for real this time.
https://github.com/halsafar/BeatSaberSongBrowser/releases/tag/5.2.0

@Xplox55 - We took down the old PP data.  New version fixes this

@trinode 
The playlist will self heal.  The important notes are in that release page but here they are again for reference:

Favorites were broken in the previous few builds. Your favorites playlist will self heal if you add or remove a song (causing it to save). Now restart the game and it should be functional again. No songs will be lost.


Let me know if that fixes this for you.

**Comment by Migushthe2nd** [comment] 2019-06-27 08:51
Sorting by pp and stars still does not seem to work

**Comment by WesVleuten** [comment] 2019-06-27 09:04
They just did network maintenance at the CDN. During that time the delivery of assets was a bit spotty. It should be resolved. Could you try again @Migushthe2nd ?

**Comment by Migushthe2nd** [comment] 2019-06-27 09:41
Nope. Sorting from lowest to highest sorts them from Z-A, but from highest to lowest does nohing (for both pp and stars)

**Comment by halsafar** [comment] 2019-06-27 14:05
Are you sure you updated to 5.2.0 or higher?  The update isnt on BeatMods yet.  Otherwise provide more info since everyone testing 5.2.0+ has no issues here.

**Comment by Migushthe2nd** [comment] 2019-06-28 13:31
I am on 5.2.0

**Comment by halsafar** [comment] 2019-06-28 14:47
In the next version I am going to disable PP and Star sorting if the BeatStar data from Wes hasn't downloaded or failed. This will at least make it clear that the data is missing if that is the problem.

**Comment by Xplox55** [comment] 2019-07-19 10:34
Hello again all,

Keep everything below with a grain of salt, I have yet to do much troubleshooting and should probably perform a reinstall of the game, as I haven't played for a few weeks, ran the mod assistant and IPA.exe to get things up and running.

Favorites seem to currently be in a much better state, for me at least. Most of my favorites are now showing (I opened the game and it said 663 songs, 0 downloaded.) I selected Download and it did download ~500 of them. Granted, the songs were already all there in my CustomSongs folder. Although quite a few of my most played favorites songs are not showing up in the list for some reason. (I can search them in CustomSongs in game but they don't show up in my favorites list.)

Adding to favorites, unfortunately, does not seem to be working for me.

Sorting by PP appears to work along with most of the rest of the sorting options I had tried. Yay!

One thing to note, my play count does seem to be off, as in either all my plays were reset or it's not being sorted properly. Anybody know which might be the case?

Thank you again for all the hard work on this!

**Comment by halsafar** [comment] 2019-12-17 03:43
Sorry to put an end to our excellent conversation.  I've completed removed all code regarding favorites from Song Browser.  Beat Saber itself has a favorite system which SongBrowser now uses.  Add/Remove favorites is now Beat Sabers responsibility. Your existing favorites get migrated on first load.  Filtering by favorites still work.  We can open new issues if some interaction there is broken.

**Closed by halsafar** 2019-12-17 03:43 UTC
Labels: bug, question
