### ISSUE TITLE
(5.2.2) Favorites not synchronising

### ISSUE THREAD

**Issue by trinode** [halsafar/BeatSaberSongBrowser#82] opened 2019-06-30 17:18 UTC
I thought favorites weren't being added, but it seems they are but the SongBrowser favorites list isn't getting refreshed,

I tested by adding a song, looking at the favourites list, it wasn't there, I went back and saw the favourite button was back in a state of add, not remove, so I added again, and repeated one more time, it did not show up.

I then quit Beat Saber (rift S tracking camera issues), loaded beat saber again and checked the favorites, The song I was trying to add was there 3 times.

So it seems to work mostly but not update the playlist in game.

**Comment by halsafar** [comment] 2019-07-18 03:51
Is this still an issue in 5.3.1?  I am having trouble reproducing this.

**Comment by trinode** [comment] 2019-07-19 23:09
Yep still an issue:-

- Go to custom songs sorted by newest
- add the newest song to faves
- go look at the songbrowser faves playlist, sorted by newest (not there)
- quit game
- open game
- go to songbrowser faves, sorted by newest, it's there

**Comment by halsafar** [comment] 2019-07-21 18:12
@trinode  When you say "go look at the songbrowser faves playlist" do you mean select the level pack `SongBrowserPluginFavorites`?  If so, that level pack is generated by the Downloader plugin and doesn't update automatically.  

I think the real issue here is that Downloader and SongBrowser are not sharing favorites and it is confusing having two places.  I'll see about sorting that out.

**Comment by halsafar** [comment] 2019-12-17 03:40
Closing this only because SongBrowser no longer manages favorites in favor of the new in-game favorites system. Your existing favorites get migrated to the new in-game favorites on first load. You can still filter by Favorites but again it now uses the in-game favorites list.

**Closed by halsafar** 2019-12-17 03:40 UTC
Labels: bug, question
