### ISSUE TITLE
crash when HideMessagesForPerformance disabled and Search already has a song cached

### ISSUE THREAD

**Issue by thelightdesigner** [halsafar/BeatSaberSongBrowser#159] opened 2021-07-19 22:40 UTC
crash when HideMessagesForPerformance disabled and Search already has a song cached

![ipa](https://user-images.githubusercontent.com/48635344/126235991-9f47b8e4-617d-425d-ab49-9531dd8d00dd.jpg)
[`_latest.log`](https://github.com/halsafar/BeatSaberSongBrowser/files/6844241/_latest.log)

**Comment by thelightdesigner** [comment] 2021-07-20 00:16
reproduce:
 - search for a song
 - close the game
 - set Beat Saber IPA.json to how it is shown in the image
 - reopen 
 - check logs

**Comment by halsafar** [comment] 2021-08-31 22:34
Unable to reproduce in 1.16.4 or 1.17.0.  Closing for now.  If it happens again see if you can capture the latest.log.

**Closed by halsafar** 2021-08-31 22:34 UTC
